\copy aka_name to 'TARGET_CSV_PATH/aka_name.csv' csv
\copy aka_title to 'TARGET_CSV_PATH/aka_title.csv' csv
\copy cast_info to 'TARGET_CSV_PATH/cast_info.csv' csv
\copy char_name to 'TARGET_CSV_PATH/char_name.csv' csv
\copy comp_cast_type to 'TARGET_CSV_PATH/comp_cast_type.csv' csv
\copy company_name to 'TARGET_CSV_PATH/company_name.csv' csv
\copy company_type to 'TARGET_CSV_PATH/company_type.csv' csv
\copy complete_cast to 'TARGET_CSV_PATH/complete_cast.csv' csv
\copy info_type to 'TARGET_CSV_PATH/info_type.csv' csv
\copy keyword to 'TARGET_CSV_PATH/keyword.csv' csv
\copy kind_type to 'TARGET_CSV_PATH/kind_type.csv' csv
\copy link_type to 'TARGET_CSV_PATH/link_type.csv' csv
\copy movie_companies to 'TARGET_CSV_PATH/movie_companies.csv' csv
\copy movie_info to 'TARGET_CSV_PATH/movie_info.csv' csv
\copy movie_info_idx to 'TARGET_CSV_PATH/movie_info_idx.csv' csv
\copy movie_keyword to 'TARGET_CSV_PATH/movie_keyword.csv' csv
\copy movie_link to 'TARGET_CSV_PATH/movie_link.csv' csv
\copy name to 'TARGET_CSV_PATH/name.csv' csv
\copy person_info to 'TARGET_CSV_PATH/person_info.csv' csv
\copy role_type to 'TARGET_CSV_PATH/role_type.csv' csv
\copy title to 'TARGET_CSV_PATH/title.csv' csv
