\copy aka_name to '/home/pei/Project/benchmarks/imdb_s/aka_name.csv' csv
\copy aka_title to '/home/pei/Project/benchmarks/imdb_s/aka_title.csv' csv
\copy cast_info to '/home/pei/Project/benchmarks/imdb_s/cast_info.csv' csv
\copy char_name to '/home/pei/Project/benchmarks/imdb_s/char_name.csv' csv
\copy comp_cast_type to '/home/pei/Project/benchmarks/imdb_s/comp_cast_type.csv' csv
\copy company_name to '/home/pei/Project/benchmarks/imdb_s/company_name.csv' csv
\copy company_type to '/home/pei/Project/benchmarks/imdb_s/company_type.csv' csv
\copy complete_cast to '/home/pei/Project/benchmarks/imdb_s/complete_cast.csv' csv
\copy info_type to '/home/pei/Project/benchmarks/imdb_s/info_type.csv' csv
\copy keyword to '/home/pei/Project/benchmarks/imdb_s/keyword.csv' csv
\copy kind_type to '/home/pei/Project/benchmarks/imdb_s/kind_type.csv' csv
\copy link_type to '/home/pei/Project/benchmarks/imdb_s/link_type.csv' csv
\copy movie_companies to '/home/pei/Project/benchmarks/imdb_s/movie_companies.csv' csv
\copy movie_info to '/home/pei/Project/benchmarks/imdb_s/movie_info.csv' csv
\copy movie_info_idx to '/home/pei/Project/benchmarks/imdb_s/movie_info_idx.csv' csv
\copy movie_keyword to '/home/pei/Project/benchmarks/imdb_s/movie_keyword.csv' csv
\copy movie_link to '/home/pei/Project/benchmarks/imdb_s/movie_link.csv' csv
\copy name to '/home/pei/Project/benchmarks/imdb_s/name.csv' csv
\copy person_info to '/home/pei/Project/benchmarks/imdb_s/person_info.csv' csv
\copy role_type to '/home/pei/Project/benchmarks/imdb_s/role_type.csv' csv
\copy title to '/home/pei/Project/benchmarks/imdb_s/title.csv' csv
