\copy aka_name to '/home/pei/Project/benchmarks/imdb_job-postgres/aka_name.csv' csv
\copy aka_title to '/home/pei/Project/benchmarks/imdb_job-postgres/aka_title.csv' csv
\copy cast_info to '/home/pei/Project/benchmarks/imdb_job-postgres/cast_info.csv' csv
\copy char_name to '/home/pei/Project/benchmarks/imdb_job-postgres/char_name.csv' csv
\copy comp_cast_type to '/home/pei/Project/benchmarks/imdb_job-postgres/comp_cast_type.csv' csv
\copy company_name to '/home/pei/Project/benchmarks/imdb_job-postgres/company_name.csv' csv
\copy company_type to '/home/pei/Project/benchmarks/imdb_job-postgres/company_type.csv' csv
\copy complete_cast to '/home/pei/Project/benchmarks/imdb_job-postgres/complete_cast.csv' csv
\copy info_type to '/home/pei/Project/benchmarks/imdb_job-postgres/info_type.csv' csv
\copy keyword to '/home/pei/Project/benchmarks/imdb_job-postgres/keyword.csv' csv
\copy kind_type to '/home/pei/Project/benchmarks/imdb_job-postgres/kind_type.csv' csv
\copy link_type to '/home/pei/Project/benchmarks/imdb_job-postgres/link_type.csv' csv
\copy movie_companies to '/home/pei/Project/benchmarks/imdb_job-postgres/movie_companies.csv' csv
\copy movie_info to '/home/pei/Project/benchmarks/imdb_job-postgres/movie_info.csv' csv
\copy movie_info_idx to '/home/pei/Project/benchmarks/imdb_job-postgres/movie_info_idx.csv' csv
\copy movie_keyword to '/home/pei/Project/benchmarks/imdb_job-postgres/movie_keyword.csv' csv
\copy movie_link to '/home/pei/Project/benchmarks/imdb_job-postgres/movie_link.csv' csv
\copy name to '/home/pei/Project/benchmarks/imdb_job-postgres/name.csv' csv
\copy person_info to '/home/pei/Project/benchmarks/imdb_job-postgres/person_info.csv' csv
\copy role_type to '/home/pei/Project/benchmarks/imdb_job-postgres/role_type.csv' csv
\copy title to '/home/pei/Project/benchmarks/imdb_job-postgres/title.csv' csv
