#!/usr/bin/env python3
"""
Group JOB benchmark queries based on their characteristics:
1. Number of tables used
2. Number of FK-PK joins
3. Number of FK-FK joins
4. Range of table row counts
5. Number of filters

Reads from query_analysis.json generated by analyze_queries.py
"""

import json
from pathlib import Path
from collections import defaultdict

BASE_DIR = Path(__file__).parent
ANALYSIS_FILE = BASE_DIR / "query_analysis.json"


def load_analysis():
    """Load query analysis results."""
    with open(ANALYSIS_FILE, 'r') as f:
        return json.load(f)


def group_by_num_tables(results):
    """Group queries by the number of tables used."""
    groups = defaultdict(list)
    for query, data in results.items():
        groups[data["num_tables"]].append(query)
    return dict(sorted(groups.items()))


def group_by_fk_pk_joins(results):
    """Group queries by the number of FK-PK joins."""
    groups = defaultdict(list)
    for query, data in results.items():
        groups[data["fk_pk_joins"]].append(query)
    return dict(sorted(groups.items()))


def group_by_fk_fk_joins(results):
    """Group queries by the number of FK-FK joins."""
    groups = defaultdict(list)
    for query, data in results.items():
        groups[data["fk_fk_joins"]].append(query)
    return dict(sorted(groups.items()))


def categorize_row_range(min_rows, max_rows):
    """
    Categorize the row count range into buckets.
    Uses log-scale buckets for both min and max.
    """
    def log_bucket(n):
        if n == 0:
            return "0"
        elif n < 100:
            return "<100"
        elif n < 1000:
            return "100-1K"
        elif n < 10000:
            return "1K-10K"
        elif n < 100000:
            return "10K-100K"
        elif n < 1000000:
            return "100K-1M"
        elif n < 10000000:
            return "1M-10M"
        else:
            return "10M+"

    min_bucket = log_bucket(min_rows)
    max_bucket = log_bucket(max_rows)
    return f"{min_bucket} to {max_bucket}"


def group_by_row_range(results):
    """Group queries by their table row count range."""
    groups = defaultdict(list)
    for query, data in results.items():
        category = categorize_row_range(data["min_rows"], data["max_rows"])
        groups[category].append(query)

    # Sort by min bucket then max bucket
    bucket_order = {"0": 0, "<100": 1, "100-1K": 2, "1K-10K": 3, "10K-100K": 4,
                    "100K-1M": 5, "1M-10M": 6, "10M+": 7}

    def sort_key(item):
        parts = item[0].split(" to ")
        return (bucket_order.get(parts[0], 99), bucket_order.get(parts[1], 99))

    return dict(sorted(groups.items(), key=sort_key))


def categorize_filters(num_filters):
    """Categorize number of filters into buckets."""
    if num_filters <= 2:
        return "1-2"
    elif num_filters <= 5:
        return "3-5"
    elif num_filters <= 8:
        return "6-8"
    elif num_filters <= 11:
        return "9-11"
    else:
        return "12+"


def group_by_num_filters(results):
    """Group queries by the number of filters."""
    groups = defaultdict(list)
    for query, data in results.items():
        category = categorize_filters(data["num_filters"])
        groups[category].append(query)

    # Sort by filter range
    order = {"1-2": 0, "3-5": 1, "6-8": 2, "9-11": 3, "12+": 4}
    return dict(sorted(groups.items(), key=lambda x: order.get(x[0], 99)))


def sort_queries(queries):
    """Sort query names naturally (1a, 1b, 2a, etc.)."""
    import re

    def sort_key(name):
        match = re.match(r'(\d+)([a-z]*)', name)
        if match:
            return (int(match.group(1)), match.group(2))
        return (999, name)

    return sorted(queries, key=sort_key)


def print_group(title, groups):
    """Print a grouping with formatted output."""
    print(f"\n{'='*80}")
    print(f"GROUPED BY: {title}")
    print('='*80)

    for key, queries in groups.items():
        sorted_queries = sort_queries(queries)
        print(f"\n[{key}] ({len(queries)} queries)")
        print(f"  {', '.join(sorted_queries)}")


def print_summary_statistics(results):
    """Print summary statistics about the queries."""
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    num_tables = [r["num_tables"] for r in results.values()]
    fk_pk = [r["fk_pk_joins"] for r in results.values()]
    fk_fk = [r["fk_fk_joins"] for r in results.values()]
    filters = [r["num_filters"] for r in results.values()]
    min_rows = [r["min_rows"] for r in results.values()]
    max_rows = [r["max_rows"] for r in results.values()]

    def stats(values, name):
        return f"{name}: min={min(values)}, max={max(values)}, avg={sum(values)/len(values):.1f}"

    print(stats(num_tables, "Tables"))
    print(stats(fk_pk, "FK-PK joins"))
    print(stats(fk_fk, "FK-FK joins"))
    print(stats(filters, "Filters"))
    print(f"Min rows: min={min(min_rows):,}, max={max(min_rows):,}")
    print(f"Max rows: min={min(max_rows):,}, max={max(max_rows):,}")
    print(f"Total queries: {len(results)}")


def save_groupings(results, output_file):
    """Save all groupings to a JSON file."""
    groupings = {
        "by_num_tables": group_by_num_tables(results),
        "by_fk_pk_joins": group_by_fk_pk_joins(results),
        "by_fk_fk_joins": group_by_fk_fk_joins(results),
        "by_row_range": group_by_row_range(results),
        "by_num_filters": group_by_num_filters(results)
    }

    # Convert keys to strings for JSON serialization
    def convert_keys(d):
        return {str(k): sort_queries(v) for k, v in d.items()}

    groupings = {k: convert_keys(v) for k, v in groupings.items()}

    with open(output_file, 'w') as f:
        json.dump(groupings, f, indent=2)

    print(f"\nGroupings saved to {output_file}")


def main():
    results = load_analysis()

    print_summary_statistics(results)

    # Group by each criterion
    print_group("Number of Tables", group_by_num_tables(results))
    print_group("FK-PK Joins", group_by_fk_pk_joins(results))
    print_group("FK-FK Joins", group_by_fk_fk_joins(results))
    print_group("Table Row Count Range (min to max)", group_by_row_range(results))
    print_group("Number of Filters", group_by_num_filters(results))

    # Save to file
    output_file = BASE_DIR / "query_groupings.json"
    save_groupings(results, output_file)


if __name__ == "__main__":
    main()
