# change user_name
psql -c "alter table aka_name owner to $user_name;"
psql -c "alter table aka_title owner to $user_name;"
psql -c "alter table cast_info owner to $user_name;"
psql -c "alter table char_name owner to $user_name;"
psql -c "alter table comp_cast_type owner to $user_name;"
psql -c "alter table company_name owner to $user_name;"
psql -c "alter table company_type owner to $user_name;"
psql -c "alter table complete_cast owner to $user_name;"
psql -c "alter table info_type owner to $user_name;"
psql -c "alter table keyword owner to $user_name;"
psql -c "alter table kind_type owner to $user_name;"
psql -c "alter table link_type owner to $user_name;"
psql -c "alter table movie_companies owner to $user_name;"
psql -c "alter table movie_info owner to $user_name;"
psql -c "alter table movie_info_idx owner to $user_name;"
psql -c "alter table movie_keyword owner to $user_name;"
psql -c "alter table movie_link owner to $user_name;"
psql -c "alter table name owner to $user_name;"
psql -c "alter table person_info owner to $user_name;"
psql -c "alter table role_type owner to $user_name;"
psql -c "alter table title owner to $user_name;"

